// This file is generated by removing the old proc-macro derives. Keep the lists in sync with the AST/token definitions.
macro_rules! impl_spanned_struct {
    ($name:ident $(<$lifetime:lifetime>)?) => {
        impl$(<$lifetime>)? crate::pos::Spanned for $name$(<$lifetime>)? {
            #[inline]
            fn span(&self) -> &Span {
                &self.span
            }
        }
    };
}

macro_rules! impl_spanned_enum {
    ($name:ident $(<$lifetime:lifetime>)? { tuple: [$($tuple:ident,)*], unit: [$($unit:ident,)*], }) => {
        impl$(<$lifetime>)? crate::pos::Spanned for $name$(<$lifetime>)? {
            #[inline]
            fn span(&self) -> &Span {
                match self {
                    $(Self::$tuple(value) => value.span(),)*
                    $(Self::$unit => panic!("not implemented"),)*
                }
            }
        }
    };
}

// Spanned
impl_spanned_struct!(AnPlusB);
impl_spanned_struct!(AtRule<'a>);
impl_spanned_enum!(AtRulePrelude<'a> {
    tuple: [Charset, ColorProfile, Container, CounterStyle, CustomMedia, CustomSelector, Document, FontFeatureValues, FontPaletteValues, Import, Keyframes, Layer, LessImport, LessPlugin, Media, Namespace, Nest, Page, PositionTry, Property, SassAtRoot, SassContent, SassEach, SassExpr, SassExtend, SassFor, SassForward, SassFunction, SassImport, SassInclude, SassMixin, SassUse, Scope, ScrollTimeline, Supports, Unknown, ],
    unit: [],
});
impl_spanned_struct!(AttributeSelector<'a>);
impl_spanned_struct!(AttributeSelectorMatcher);
impl_spanned_struct!(AttributeSelectorModifier<'a>);
impl_spanned_enum!(AttributeSelectorValue<'a> {
    tuple: [Ident, Str, Number, Dimension, Percentage, LessEscapedStr, TokenSeq, ],
    unit: [],
});
impl_spanned_struct!(BracketBlock<'a>);
impl_spanned_struct!(Calc<'a>);
impl_spanned_struct!(CalcOperator);
impl_spanned_enum!(CalcOperatorKind {
    tuple: [],
    unit: [Plus, Minus, Multiply, Division, Modulo, ],
});
impl_spanned_struct!(ClassSelector<'a>);
impl_spanned_enum!(ColorProfilePrelude<'a> {
    tuple: [DashedIdent, DeviceCmyk, ],
    unit: [],
});
impl_spanned_struct!(Combinator);
impl_spanned_struct!(ComplexSelector<'a>);
impl_spanned_enum!(ComplexSelectorChild<'a> {
    tuple: [CompoundSelector, Combinator, ],
    unit: [],
});
impl_spanned_enum!(ComponentValue<'a> {
    tuple: [BracketBlock, Calc, Delimiter, Dimension, Function, HexColor, IdSelector, ImportantAnnotation, InterpolableIdent, InterpolableStr, LayerName, LessAnonymousMixin, LessBinaryOperation, LessCondition, LessDetachedRuleset, LessEscapedStr, LessJavaScriptSnippet, LessList, LessMixinCall, LessNamespaceValue, LessVariableCall, LessNegativeValue, LessParenthesizedOperation, LessPercentKeyword, LessPropertyVariable, LessVariable, LessVariableVariable, Number, Percentage, Placeholder, PostcssSimpleVar, Ratio, SassArbitraryArgument, SassBinaryExpression, SassKeywordArgument, SassList, SassMap, SassQualifiedName, SassNestingDeclaration, SassParenthesizedExpression, SassParentSelector, SassUnaryExpression, SassVariable, TokenWithSpan, UnicodeRange, Url, ],
    unit: [],
});
impl_spanned_struct!(ComponentValues<'a>);
impl_spanned_struct!(CompoundSelector<'a>);
impl_spanned_struct!(CompoundSelectorList<'a>);
impl_spanned_struct!(ContainerCondition<'a>);
impl_spanned_enum!(ContainerConditionKind<'a> {
    tuple: [QueryInParens, And, Or, Not, ],
    unit: [],
});
impl_spanned_struct!(ContainerConditionAnd<'a>);
impl_spanned_struct!(ContainerConditionNot<'a>);
impl_spanned_struct!(ContainerConditionOr<'a>);
impl_spanned_struct!(ContainerPrelude<'a>);
impl_spanned_struct!(CustomMedia<'a>);
impl_spanned_enum!(CustomMediaValue<'a> {
    tuple: [MediaQueryList, True, False, ],
    unit: [],
});
impl_spanned_struct!(CustomSelector<'a>);
impl_spanned_struct!(CustomSelectorArg<'a>);
impl_spanned_struct!(CustomSelectorArgs<'a>);
impl_spanned_struct!(CustomSelectorPrelude<'a>);
impl_spanned_struct!(Declaration<'a>);
impl_spanned_struct!(Delimiter);
impl_spanned_struct!(Dimension<'a>);
impl_spanned_enum!(DimensionKind {
    tuple: [],
    unit: [Length, Angle, Duration, Frequency, Resolution, Flex, Unknown, ],
});
impl_spanned_struct!(DocumentPrelude<'a>);
impl_spanned_enum!(DocumentPreludeMatcher<'a> {
    tuple: [Url, Function, ],
    unit: [],
});
impl_spanned_enum!(FontFamilyName<'a> {
    tuple: [Str, Unquoted, ],
    unit: [],
});
impl_spanned_struct!(Function<'a>);
impl_spanned_enum!(FunctionName<'a> {
    tuple: [Ident, SassQualifiedName, LessListFunction, LessFormatFunction, ],
    unit: [],
});
impl_spanned_struct!(HexColor<'a>);
impl_spanned_struct!(Ident<'a>);
impl_spanned_struct!(ImportPrelude<'a>);
impl_spanned_enum!(ImportPreludeHref<'a> {
    tuple: [Str, Url, Function, ],
    unit: [],
});
impl_spanned_enum!(ImportPreludeLayer<'a> {
    tuple: [Empty, WithName, ],
    unit: [],
});
impl_spanned_struct!(ImportPreludeSupports<'a>);
impl_spanned_enum!(ImportPreludeSupportsKind<'a> {
    tuple: [SupportsCondition, Declaration, ],
    unit: [],
});
impl_spanned_enum!(InterpolableIdent<'a> {
    tuple: [Literal, SassInterpolated, LessInterpolated, Placeholder, ],
    unit: [],
});
impl_spanned_struct!(Placeholder<'a>);
impl_spanned_struct!(InterpolableIdentStaticPart<'a>);
impl_spanned_enum!(InterpolableStr<'a> {
    tuple: [Literal, SassInterpolated, LessInterpolated, ],
    unit: [],
});
impl_spanned_struct!(InterpolableStrStaticPart<'a>);
impl_spanned_struct!(InterpolableUrlStaticPart<'a>);
impl_spanned_struct!(IdSelector<'a>);
impl_spanned_struct!(ImportantAnnotation<'a>);
impl_spanned_struct!(KeyframeBlock<'a>);
impl_spanned_enum!(KeyframeSelector<'a> {
    tuple: [Ident, Percentage, ],
    unit: [],
});
impl_spanned_enum!(KeyframesName<'a> {
    tuple: [Ident, Str, LessVariable, LessEscapedStr, ],
    unit: [],
});
impl_spanned_enum!(LanguageRange<'a> {
    tuple: [Str, Ident, ],
    unit: [],
});
impl_spanned_struct!(LanguageRangeList<'a>);
impl_spanned_struct!(LayerName<'a>);
impl_spanned_struct!(LayerNames<'a>);
impl_spanned_struct!(LessBinaryCondition<'a>);
impl_spanned_struct!(LessBinaryConditionOperator);
impl_spanned_struct!(LessBinaryOperation<'a>);
impl_spanned_enum!(LessCondition<'a> {
    tuple: [Binary, Negated, Parenthesized, Value, ],
    unit: [],
});
impl_spanned_struct!(LessAnonymousMixin<'a>);
impl_spanned_struct!(LessConditionalQualifiedRule<'a>);
impl_spanned_struct!(LessConditions<'a>);
impl_spanned_struct!(LessDetachedRuleset<'a>);
impl_spanned_struct!(LessEscapedStr<'a>);
impl_spanned_struct!(LessExtend<'a>);
impl_spanned_struct!(LessExtendList<'a>);
impl_spanned_struct!(LessExtendRule<'a>);
impl_spanned_struct!(LessFormatFunction);
impl_spanned_struct!(LessImportOptions<'a>);
impl_spanned_struct!(LessImportPrelude<'a>);
impl_spanned_struct!(LessInterpolatedIdent<'a>);
impl_spanned_enum!(LessInterpolatedIdentElement<'a> {
    tuple: [Variable, Property, Static, ],
    unit: [],
});
impl_spanned_struct!(LessInterpolatedStr<'a>);
impl_spanned_enum!(LessInterpolatedStrElement<'a> {
    tuple: [Variable, Property, Static, ],
    unit: [],
});
impl_spanned_struct!(LessJavaScriptSnippet<'a>);
impl_spanned_struct!(LessList<'a>);
impl_spanned_struct!(LessListFunction);
impl_spanned_struct!(LessLookup<'a>);
impl_spanned_enum!(LessLookupName<'a> {
    tuple: [LessVariable, LessVariableVariable, LessPropertyVariable, LessPropertyInterpolation, Ident, ],
    unit: [],
});
impl_spanned_struct!(LessLookups<'a>);
impl_spanned_enum!(LessMixinArgument<'a> {
    tuple: [Named, Value, Variadic, ],
    unit: [],
});
impl_spanned_struct!(LessMixinArguments<'a>);
impl_spanned_struct!(LessMixinCall<'a>);
impl_spanned_struct!(LessMixinCallee<'a>);
impl_spanned_struct!(LessMixinCalleeChild<'a>);
impl_spanned_struct!(LessMixinDefinition<'a>);
impl_spanned_enum!(LessMixinName<'a> {
    tuple: [ClassSelector, IdSelector, ],
    unit: [],
});
impl_spanned_struct!(LessMixinNamedArgument<'a>);
impl_spanned_struct!(LessMixinNamedParameter<'a>);
impl_spanned_struct!(LessMixinNamedParameterDefaultValue<'a>);
impl_spanned_enum!(LessMixinParameter<'a> {
    tuple: [Named, Unnamed, Variadic, ],
    unit: [],
});
impl_spanned_struct!(LessMixinParameters<'a>);
impl_spanned_enum!(LessMixinParameterName<'a> {
    tuple: [Variable, PropertyVariable, ],
    unit: [],
});
impl_spanned_struct!(LessMixinUnnamedParameter<'a>);
impl_spanned_struct!(LessMixinVariadicArgument<'a>);
impl_spanned_struct!(LessMixinVariadicParameter<'a>);
impl_spanned_struct!(LessNamespaceValue<'a>);
impl_spanned_enum!(LessNamespaceValueCallee<'a> {
    tuple: [LessMixinCall, LessVariable, ],
    unit: [],
});
impl_spanned_struct!(LessNegatedCondition<'a>);
impl_spanned_struct!(LessNegativeValue<'a>);
impl_spanned_struct!(LessOperationOperator);
impl_spanned_struct!(LessParenthesizedCondition<'a>);
impl_spanned_struct!(LessParenthesizedOperation<'a>);
impl_spanned_struct!(LessPercentKeyword);
impl_spanned_struct!(LessPlugin<'a>);
impl_spanned_enum!(LessPluginPath<'a> {
    tuple: [Str, Url, ],
    unit: [],
});
impl_spanned_struct!(LessPropertyInterpolation<'a>);
impl_spanned_struct!(LessPropertyMerge);
impl_spanned_enum!(LessPropertyMergeKind {
    tuple: [],
    unit: [Comma, Space, ],
});
impl_spanned_struct!(LessPropertyVariable<'a>);
impl_spanned_struct!(LessVariable<'a>);
impl_spanned_struct!(LessVariableCall<'a>);
impl_spanned_struct!(LessVariableDeclaration<'a>);
impl_spanned_struct!(LessVariableInterpolation<'a>);
impl_spanned_struct!(LessVariableVariable<'a>);
impl_spanned_struct!(MediaAnd<'a>);
impl_spanned_struct!(MediaCondition<'a>);
impl_spanned_struct!(MediaConditionAfterMediaType<'a>);
impl_spanned_enum!(MediaConditionKind<'a> {
    tuple: [MediaInParens, And, Or, Not, ],
    unit: [],
});
impl_spanned_enum!(MediaFeature<'a> {
    tuple: [Plain, Boolean, Range, RangeInterval, ],
    unit: [],
});
impl_spanned_struct!(MediaFeatureComparison);
impl_spanned_enum!(MediaFeatureName<'a> {
    tuple: [Ident, PostcssSimpleVar, SassVariable, ],
    unit: [],
});
impl_spanned_struct!(MediaFeatureBoolean<'a>);
impl_spanned_struct!(MediaFeaturePlain<'a>);
impl_spanned_struct!(MediaFeatureRange<'a>);
impl_spanned_struct!(MediaFeatureRangeInterval<'a>);
impl_spanned_struct!(MediaInParens<'a>);
impl_spanned_enum!(MediaInParensKind<'a> {
    tuple: [MediaCondition, MediaFeature, GeneralEnclosed, SassInterpolation, ],
    unit: [],
});
impl_spanned_struct!(MediaNot<'a>);
impl_spanned_struct!(MediaOr<'a>);
impl_spanned_enum!(MediaQuery<'a> {
    tuple: [ConditionOnly, WithType, Function, LessVariable, LessNamespaceValue, ],
    unit: [],
});
impl_spanned_struct!(MediaQueryList<'a>);
impl_spanned_struct!(MediaQueryWithType<'a>);
impl_spanned_struct!(NamespacePrelude<'a>);
impl_spanned_enum!(NamespacePreludeUri<'a> {
    tuple: [Str, Url, ],
    unit: [],
});
impl_spanned_struct!(NestingSelector<'a>);
impl_spanned_struct!(NsPrefix<'a>);
impl_spanned_enum!(NsPrefixKind<'a> {
    tuple: [Ident, Universal, ],
    unit: [],
});
impl_spanned_struct!(NsPrefixUniversal);
impl_spanned_struct!(Nth<'a>);
impl_spanned_enum!(NthIndex<'a> {
    tuple: [Odd, Even, Integer, AnPlusB, ],
    unit: [],
});
impl_spanned_struct!(NthMatcher<'a>);
impl_spanned_struct!(Number<'a>);
impl_spanned_struct!(PageSelector<'a>);
impl_spanned_struct!(PageSelectorList<'a>);
impl_spanned_struct!(Percentage<'a>);
impl_spanned_struct!(PostcssSimpleVar<'a>);
impl_spanned_struct!(PostcssSimpleVarDeclaration<'a>);
impl_spanned_struct!(PseudoClassSelector<'a>);
impl_spanned_struct!(PseudoClassSelectorArg<'a>);
impl_spanned_enum!(PseudoClassSelectorArgKind<'a> {
    tuple: [CompoundSelector, CompoundSelectorList, Ident, LanguageRangeList, Nth, Number, RelativeSelectorList, SelectorList, LessExtendList, TokenSeq, ],
    unit: [],
});
impl_spanned_struct!(PseudoElementSelector<'a>);
impl_spanned_struct!(PseudoElementSelectorArg<'a>);
impl_spanned_enum!(PseudoElementSelectorArgKind<'a> {
    tuple: [CompoundSelector, CompoundSelectorList, Ident, TokenSeq, ],
    unit: [],
});
impl_spanned_struct!(PseudoPage<'a>);
impl_spanned_struct!(QualifiedRule<'a>);
impl_spanned_struct!(QueryInParens<'a>);
impl_spanned_enum!(QueryInParensKind<'a> {
    tuple: [ContainerCondition, SizeFeature, StyleQuery, ScrollState, ],
    unit: [],
});
impl_spanned_struct!(Ratio<'a>);
impl_spanned_struct!(RelativeSelector<'a>);
impl_spanned_struct!(RelativeSelectorList<'a>);
impl_spanned_struct!(SassArbitraryArgument<'a>);
impl_spanned_struct!(SassArbitraryParameter<'a>);
impl_spanned_struct!(SassAtRoot<'a>);
impl_spanned_enum!(SassAtRootKind<'a> {
    tuple: [Selector, Query, ],
    unit: [],
});
impl_spanned_struct!(SassAtRootQuery<'a>);
impl_spanned_struct!(SassAtRootQueryModifier);
impl_spanned_enum!(SassAtRootQueryRule<'a> {
    tuple: [Ident, Str, ],
    unit: [],
});
impl_spanned_struct!(SassBinaryExpression<'a>);
impl_spanned_struct!(SassBinaryOperator);
impl_spanned_struct!(SassConditionalClause<'a>);
impl_spanned_struct!(SassContent<'a>);
impl_spanned_struct!(SassEach<'a>);
impl_spanned_struct!(SassExtend<'a>);
impl_spanned_struct!(SassFlag<'a>);
impl_spanned_struct!(SassFor<'a>);
impl_spanned_struct!(SassForBoundary);
impl_spanned_enum!(SassForBoundaryKind {
    tuple: [],
    unit: [Inclusive, Exclusive, ],
});
impl_spanned_struct!(SassForward<'a>);
impl_spanned_enum!(SassForwardMember<'a> {
    tuple: [Ident, Variable, ],
    unit: [],
});
impl_spanned_struct!(SassForwardPrefix<'a>);
impl_spanned_struct!(SassForwardVisibility<'a>);
impl_spanned_struct!(SassForwardVisibilityModifier);
impl_spanned_enum!(SassForwardVisibilityModifierKind {
    tuple: [],
    unit: [Hide, Show, ],
});
impl_spanned_struct!(SassFunction<'a>);
impl_spanned_struct!(SassIfAtRule<'a>);
impl_spanned_struct!(SassImportPrelude<'a>);
impl_spanned_struct!(SassInclude<'a>);
impl_spanned_struct!(SassIncludeArgs<'a>);
impl_spanned_struct!(SassIncludeContentBlockParams<'a>);
impl_spanned_struct!(SassInterpolatedIdent<'a>);
impl_spanned_enum!(SassInterpolatedIdentElement<'a> {
    tuple: [Expression, Static, ],
    unit: [],
});
impl_spanned_struct!(SassInterpolatedStr<'a>);
impl_spanned_enum!(SassInterpolatedStrElement<'a> {
    tuple: [Expression, Static, ],
    unit: [],
});
impl_spanned_struct!(SassInterpolatedUrl<'a>);
impl_spanned_enum!(SassInterpolatedUrlElement<'a> {
    tuple: [Expression, Static, ],
    unit: [],
});
impl_spanned_struct!(SassKeywordArgument<'a>);
impl_spanned_struct!(SassList<'a>);
impl_spanned_struct!(SassMap<'a>);
impl_spanned_struct!(SassMapItem<'a>);
impl_spanned_struct!(SassMixin<'a>);
impl_spanned_struct!(SassModuleConfig<'a>);
impl_spanned_struct!(SassModuleConfigItem<'a>);
impl_spanned_enum!(SassModuleMemberName<'a> {
    tuple: [Ident, Variable, ],
    unit: [],
});
impl_spanned_struct!(SassNestingDeclaration<'a>);
impl_spanned_struct!(SassParameter<'a>);
impl_spanned_struct!(SassParameterDefaultValue<'a>);
impl_spanned_struct!(SassParameters<'a>);
impl_spanned_struct!(SassParenthesizedExpression<'a>);
impl_spanned_struct!(SassPlaceholderSelector<'a>);
impl_spanned_struct!(SassQualifiedName<'a>);
impl_spanned_struct!(SassUnaryExpression<'a>);
impl_spanned_struct!(SassUnaryOperator);
impl_spanned_struct!(SassUnnamedNamespace);
impl_spanned_struct!(SassUse<'a>);
impl_spanned_struct!(SassUseNamespace<'a>);
impl_spanned_enum!(SassUseNamespaceKind<'a> {
    tuple: [Named, Unnamed, ],
    unit: [],
});
impl_spanned_struct!(SassVariable<'a>);
impl_spanned_struct!(SassVariableDeclaration<'a>);
impl_spanned_struct!(ScopeEnd<'a>);
impl_spanned_enum!(ScopePrelude<'a> {
    tuple: [StartOnly, EndOnly, Both, ],
    unit: [],
});
impl_spanned_struct!(ScopeStart<'a>);
impl_spanned_struct!(ScopeStartWithEnd<'a>);
impl_spanned_struct!(SelectorList<'a>);
impl_spanned_struct!(SimpleBlock<'a>);
impl_spanned_enum!(SimpleSelector<'a> {
    tuple: [Class, Id, Type, Attribute, PseudoClass, PseudoElement, Nesting, SassPlaceholder, ],
    unit: [],
});
impl_spanned_enum!(Statement<'a> {
    tuple: [AtRule, Declaration, KeyframeBlock, LessConditionalQualifiedRule, LessExtendRule, LessFunctionCall, LessMixinCall, LessMixinDefinition, LessVariableCall, LessVariableDeclaration, Placeholder, PostcssSimpleVarDeclaration, QualifiedRule, SassIfAtRule, SassVariableDeclaration, UnknownSassAtRule, ],
    unit: [],
});
impl_spanned_struct!(Str<'a>);
impl_spanned_struct!(StyleCondition<'a>);
impl_spanned_enum!(StyleConditionKind<'a> {
    tuple: [StyleInParens, And, Or, Not, ],
    unit: [],
});
impl_spanned_struct!(StyleConditionAnd<'a>);
impl_spanned_struct!(StyleConditionNot<'a>);
impl_spanned_struct!(StyleConditionOr<'a>);
impl_spanned_struct!(StyleInParens<'a>);
impl_spanned_enum!(StyleInParensKind<'a> {
    tuple: [Condition, Feature, ],
    unit: [],
});
impl_spanned_enum!(StyleQuery<'a> {
    tuple: [Condition, Feature, FeatureName, ],
    unit: [],
});
impl_spanned_struct!(Stylesheet<'a>);
impl_spanned_struct!(SupportsAnd<'a>);
impl_spanned_struct!(SupportsCondition<'a>);
impl_spanned_enum!(SupportsConditionKind<'a> {
    tuple: [Not, And, Or, SupportsInParens, ],
    unit: [],
});
impl_spanned_struct!(SupportsDecl<'a>);
impl_spanned_struct!(SupportsInParens<'a>);
impl_spanned_enum!(SupportsInParensKind<'a> {
    tuple: [SupportsCondition, Feature, Selector, Function, GeneralEnclosed, Interpolation, ],
    unit: [],
});
impl_spanned_struct!(SupportsNot<'a>);
impl_spanned_struct!(SupportsOr<'a>);
impl_spanned_struct!(TagNameSelector<'a>);
impl_spanned_struct!(TokenSeq<'a>);
impl_spanned_enum!(TypeSelector<'a> {
    tuple: [TagName, Universal, ],
    unit: [],
});
impl_spanned_struct!(UnicodeRange<'a>);
impl_spanned_struct!(UniversalSelector<'a>);
impl_spanned_enum!(UnknownAtRulePrelude<'a> {
    tuple: [ComponentValue, TokenSeq, ],
    unit: [],
});
impl_spanned_struct!(UnknownSassAtRule<'a>);
impl_spanned_struct!(UnquotedFontFamilyName<'a>);
impl_spanned_struct!(Url<'a>);
impl_spanned_enum!(UrlModifier<'a> {
    tuple: [Ident, Function, ],
    unit: [],
});
impl_spanned_struct!(UrlRaw<'a>);
impl_spanned_enum!(UrlValue<'a> {
    tuple: [Raw, SassInterpolated, Str, LessEscapedStr, ],
    unit: [],
});
impl_spanned_struct!(WqName<'a>);
