[workspace]
semver_check = true
allow_dirty = true
changelog_config = "cliff.toml"

[[package]]
name = "oxc-css-parser"
version_group = "group"
changelog_include = ["oxc-css-parser-macro"]

[[package]]
name = "oxc-css-parser-macro"
version_group = "group"
changelog_update = false
