use super::token::*;

impl Token<'_> {
    pub(crate) fn symbol(&self) -> &'static str {
        use Token::*;
        match self {
            Eof(..) => "<eof>",
            Ampersand(..) => "&",
            BadStr(..) => "<bad string>",
            Asterisk(..) => "*",
            AsteriskEqual(..) => "*=",
            At(..) => "@",
            AtKeyword(..) => "<at-keyword>",
            AtLBraceVar(..) => "@{",
            BacktickCode(..) => "<backtick code>",
            Bar(..) => "|",
            BarBar(..) => "||",
            BarEqual(..) => "|=",
            CaretEqual(..) => "^=",
            Cdc(..) => "<CDC>",
            Cdo(..) => "<CDO>",
            Colon(..) => ":",
            ColonColon(..) => "::",
            Comma(..) => ",",
            Dedent(..) => "<dedent>",
            Dimension(..) => "<dimension>",
            DollarEqual(..) => "$=",
            DollarLBraceVar(..) => "${",
            DollarVar(..) => "$var",
            Dot(..) => ".",
            DotDotDot(..) => "...",
            Equal(..) => "=",
            EqualEqual(..) => "==",
            Exclamation(..) => "!",
            ExclamationEqual(..) => "!=",
            GreaterThan(..) => ">",
            GreaterThanEqual(..) => ">=",
            Hash(..) => "<hash>",
            HashLBrace(..) => "#{",
            Ident(..) => "<ident>",
            Indent(..) => "<indent>",
            LBrace(..) => "{",
            LBracket(..) => "[",
            LessThan(..) => "<",
            LessThanEqual(..) => "<=",
            Linebreak(..) => "<linebreak>",
            LParen(..) => "(",
            Minus(..) => "-",
            Number(..) => "<number>",
            NumberSign(..) => "#",
            Percent(..) => "%",
            Percentage(..) => "<percentage>",
            Placeholder(..) => "<placeholder>",
            Plus(..) => "+",
            PlusUnderscore(..) => "+_",
            Question(..) => "?",
            RBrace(..) => "}",
            RBracket(..) => "]",
            RParen(..) => ")",
            Semicolon(..) => ";",
            Solidus(..) => "/",
            Str(..) => "<string>",
            StrTemplate(..) => "<string template>",
            Tilde(..) => "~",
            TildeEqual(..) => "~=",
            Unknown(..) => "<unknown>",
            UrlRaw(..) => "<url>",
            UrlTemplate(..) => "<url template>",
        }
    }
}
