name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "crates/oxc_css_parser/Cargo.toml"
      - ".github/workflows/release.yml"
      - "release-plz.toml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  crates:
    if: github.repository == 'oxc-project/oxc-css'
    name: Publish oxc_css_parser
    runs-on: ubuntu-latest
    environment: crates
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5
        id: auth

      - name: Publish oxc_css_parser
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish -p oxc-css-parser
